name: Go

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          BUILDKIT=1 docker build --build-arg SKIP_RPC_TESTS=yes .
